### ISSUE TITLE
4.2.0 fails C compilation on windows on py27

### ISSUE THREAD

**Issue by agroszer** [zopefoundation/ExtensionClass#15]
see:
http://winbot.zope.org/builders/wineggbuilder/builds/3663/steps/release%20eggs/logs/stdio

**Comment by stephan-hof** [comment]
Thanks for reporting.
I hope the fix is as trivial as described here:
https://github.com/libgit2/pygit2/issues/53
I'll can do a pull request to fix it. However I don't know how winbot works to trigger a build there.

**Comment by agroszer** [comment]
well that task builds egg releases for pypi, apparently version 4.2.0 and 4.2.1 is borked, so someone needs to release a 4.2.2

**Comment by hannosch** [comment]
I just cut a new 4.3.0 release, so the wineggbuilder should pick that up shortly.
