### ISSUE TITLE
Build / publish wheels on Appveyor

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/ExtensionClass#19]
Checklist from https://github.com/zopefoundation/zope.proxy/issues/24:

- [x] a copy of `appveyor.yml` from `zope.interface` or similar
- [x] someone with an Appveyor account (e.g. @mgedmin ) to enable this project
- [x] encrypted PyPI upload credentials in the `appveyor.yml` (no change required from the copy in `zope.interface` if @mgedmin is the one who enables the Appveyor account)
- [x] grant **zope.wheelbuilder** PyPI rights
- [x] push the `appveyor.yml` commit to master
- [ ] (optionally) a push of a temporary branch that builds and uploads `ExtensionClass 4.3.0` wheels

**Comment by dataflake** [comment]
Fixed by commits 34d75ca2d8dda94f881dd07c94f13a48bfe80e15 and a9c045974d60d7bf610c5f4d20638c26dfb1ab6a
