### ISSUE TITLE
Pure-Python ExtensionClass wraps __parent__ but C does not

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/ExtensionClass#3]
Commit afb8488e966752dc3393124504db8eded128f99e made the C implementation of `ExtensionClass.Base` not wrap `__parent__` objects, but the pure python version still does. I ran into this while working on issue zopefoundation/Acquisition#3. (I'm working around it there for now; if I get time I'll submit a pull request here).

Compare the expected behaviour:
```
$ python

>>> import ExtensionClass
>>> class I(ExtensionClass.Base):
...     def __of__(self,o):
...         return 'wrapped'
...
>>> x = I()
>>> x.__parent__ = I()
>>> x.__parent__
<__main__.I object at 0x10f3b4290>
```

With the pure python behaviour:
```
$ PURE_PYTHON=1 python

>>> import ExtensionClass
>>> class I(ExtensionClass.Base):
...     def __of__(self, o):
...         return 'wrapped'
...
>>> x = I()
>>> x.__parent__ = I()
>>> x.__parent__
'wrapped'
```

**Comment by tseaver** [comment]
This indeed is a bug.  A PR to fix it would be nice, including adding a test that is exercised against both versions.
